### ISSUE TITLE
asynchronous update doesn't work

### ISSUE THREAD

**Issue by askhari139** [ialbert/booleannet#6]

**Comment by ialbert** [comment]
well, you need to provide more detail than that

**Comment by askhari139** [comment]
Sincere apologies for that. That was a draft that got posted by mistake. I was still investigating it at the time. Here is the actual issue. Please correct me if I am wrong in my understanding the implementation:
The current method for the asynchronous update in the package is to shuffle the update rules at each time step. That is, at every time step, multiple nodes get updated. A common way to update boolean networks asynchronously is to update only one node at a timestep, choosing randomly at each timestep which node to update. Is it possible to include this method as well? 
I tried to modify my copy of the package to do this, but I can't seem to figure out the function that is handling the actual update after the rule shuffling.

My code:
``` >>> import boolean2
>>> text = """
... GrowthFactor = True
... RTK = RAS = PI3K = RAF = MEK = PIP3 = AKT = TranscriptionFactor = False
...
... GrowthFactor* = GrowthFactor
... RTK* = GrowthFactor
... RAS* = RTK
... PI3K* = RTK or RAS
... RAF* = RAS
... MEK* = RAF
... PIP3* = PI3K
... AKT* = PIP3
... TranscriptionFactor* = MEK and AKT
... """
>>> model = boolean2.Model(text, mode='async')
>>> model.initialize()
>>> print(model.states)
[State: AKT=False, GrowthFactor=True, MEK=False, PI3K=False, PIP3=False, RAF=False, RAS=False, RTK=False, TranscriptionFactor=False]
>>> model.iterate(steps=1)
>>> print(model.states)
[State: AKT=False, GrowthFactor=True, MEK=False, PI3K=False, PIP3=False, RAF=False, RAS=False, RTK=False, TranscriptionFactor=False, State: AKT=False,GrowthFactor=True,MEK=False, PI3K=True, PIP3=True, RAF=False, RAS=False, RTK=True, TranscriptionFactor=False]
```
Multiple nodes get updated in a single iteration as you can see. I need it to update only a single node at a time.

**Comment by ialbert** [comment]
an iteration, within the software, is defined as applying all rules once. This is how it was designed to work - hence the original claim that the update does not work is flawed.

if you need to intercept the states after each rule you  may be able to do so by extending the rules as described here

https://github.com/ialbert/booleannet/blob/master/examples/samples/extend-rules.py
