### ISSUE TITLE
Knockout or expression in middle of iterations 

### ISSUE THREAD

**Issue by gsb-sai** [ialbert/booleannet#8]
hello, 
so i have a 5 node network 
a,b,c,d,e
where initial conditions are as follows
a = True
b = True 
c = False
d = False
e = False 
and i am doing the following 
`for i in range(50):
	model = Model( text=text, mode='async')
	model.initialize()
	model.iterate(steps = 100)
	model.report_cycles()
	nodes = model.nodes
	coll.collect(states=model.states, nodes=nodes )`
and i would like to change the conditions of my a and b in the middle of the process, say every 20 steps of iterations.... 
is there anyway i can do this ?

**Comment by ialbert** [comment]
you can set a callback function where you can override the values, make a global variable that keeps track of iterations

https://github.com/ialbert/booleannet/blob/master/examples/samples/extend-setvalue.py

**Comment by gsb-sai** [comment]
thank you sir for the response, 
i am new to python and i was quite unable to figure it out (tried few scenarios) on how to keep track of iterations, 
can you please help me?
thank you in advance

**Comment by ialbert** [comment]
make a global variable
```

iterations = 0


def my_func():
     global iterations
     if iterations > 10:
        print("Fizz")
     iterations += 1


```

**Comment by gsb-sai** [comment]
Thankyou sir

**Comment by gsb-sai** [comment]
hello sir, I tried the inputs given by you, A and B are my signals for the nodes C D E: 
one thing I observed in my final output in my graph is then I set values of A and B to True the activity is not reaching 1 instantly ... there are some intermediary points in sync mode and in async mode.... attaching the output figure and code I am trying for your reference. 
 my issue is the value is not setting to 1 and 0 at the given number; there are some intermediate steps 
the following is my code


text = """
#initial values
A = True
B = True
C = False
D = False
E = False

#updating rules 
A* = A
B* = B
C* = A
D* = B or C
E* = D and C
"""


def set_value(state, name,value, p):
	"Custom value setter"
	global s

	if name == 'A': # to keep a track of the iterations 
		s = s+1

	if (s >= 5 and s <=10):# and (s >= 15 and a <=20): # to set values of nodes that i want to set 
		#print name
		if name == 'A' or name == 'B':
			print('now setting node %s' % name)
			value = True
		setattr(state, name, value)
		return value
	else:
		if name == 'A' or name == 'B':
			value = False
		setattr(state, name, value)
		return value


coll=util.Collector()
for i in range(20):
	model = Model( text=text, mode='sync')
	s = 0
	model.parser.RULE_SETVALUE = set_value
	model.initialize()
	model.iterate(steps = 1000)
	coll.collect(states=model.states, nodes=model.nodes )

averages = coll.get_averages( normalize=True )
df = pd.DataFrame(averages)
csv_data = df.to_csv('adc.csv')

![adc](https://user-images.githubusercontent.com/84306327/119211699-5ad87b00-bad1-11eb-94e1-8e811b17c5de.png)

Thank you in advance
